CREATE TABLE `purchase_order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`descricao` text NOT NULL,
	`quantidade` decimal(18,5) NOT NULL,
	`quantidadeUnEstoque` decimal(18,5),
	`fatorConversao` decimal(18,5),
	`unidadeMedida` varchar(10),
	`unidadeMedidaEstoque` varchar(10),
	`dataEntrega` varchar(30),
	`dataEmissao` varchar(30),
	`estadoPedido` varchar(50),
	`estadoItem` varchar(50),
	`fornecedor` varchar(200),
	`valorTotal` decimal(18,2),
	`valorUnitario` decimal(18,5),
	`numeroPedido` varchar(20),
	`numeroItem` int,
	`codigoGrupo` varchar(10),
	`codigoCFOP` varchar(10),
	`empresaDona` varchar(100),
	`maxiprodId` bigint,
	`collectedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `purchase_order_items_id` PRIMARY KEY(`id`)
);
