CREATE TABLE `sales_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataEmissao` varchar(50),
	`dataEntrega` varchar(50),
	`dataAprovacao` varchar(50),
	`pedido` varchar(20),
	`cliente` varchar(300),
	`clienteApelido` varchar(200),
	`uf` varchar(5),
	`descricao` text,
	`estadoItem` varchar(50),
	`quantidade` decimal(18,5),
	`valorUnitario` decimal(18,5),
	`valorTotal` decimal(18,2),
	`valorContabil` decimal(18,2),
	`valorFaturar` decimal(18,2),
	`fatorConversao` decimal(18,5),
	`codigoGrupo` varchar(10),
	`idGrupoItem` bigint,
	`empresa` varchar(100),
	`representante` varchar(200),
	`segmento` varchar(100),
	`regiao` varchar(100),
	`collectedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sales_orders_id` PRIMARY KEY(`id`)
);
