CREATE TABLE `accounts_payable` (
	`id` int AUTO_INCREMENT NOT NULL,
	`maxiprodId` bigint NOT NULL,
	`estado` varchar(30) NOT NULL,
	`tipo` varchar(50),
	`valorOriginal` decimal(18,2),
	`valorLiquido` decimal(18,2),
	`valorRetido` decimal(18,2),
	`valorDeDesconto` decimal(18,2),
	`valorDeAcrescimo` decimal(18,2),
	`valorPagoLiquido` decimal(18,2),
	`emissaoData` varchar(50),
	`vencimentoData` varchar(50),
	`vencimentoOriginalData` varchar(50),
	`liquidacaoData` varchar(50),
	`referenteA` text,
	`parcela` int,
	`parcelasQuantidadeTotal` int,
	`observacoes` text,
	`documentoVinculadoNumero` varchar(100),
	`bloqueado` boolean DEFAULT false,
	`fornecedor` varchar(300),
	`centroDeCustosId` bigint,
	`contaId` bigint,
	`empresaId` bigint,
	`empresaNome` varchar(100),
	`collectedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `accounts_payable_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `accounts_receivable` (
	`id` int AUTO_INCREMENT NOT NULL,
	`maxiprodId` bigint NOT NULL,
	`estado` varchar(30) NOT NULL,
	`tipo` varchar(50),
	`valorOriginal` decimal(18,2),
	`valorLiquido` decimal(18,2),
	`valorRetido` decimal(18,2),
	`valorDeDesconto` decimal(18,2),
	`valorDeAcrescimo` decimal(18,2),
	`valorRecebidoLiquido` decimal(18,2),
	`emissaoData` varchar(50),
	`vencimentoData` varchar(50),
	`vencimentoOriginalData` varchar(50),
	`liquidacaoData` varchar(50),
	`referenteA` text,
	`parcela` int,
	`parcelasQuantidadeTotal` int,
	`observacoes` text,
	`documentoVinculadoNumero` varchar(100),
	`bloqueado` boolean DEFAULT false,
	`cliente` varchar(300),
	`centroDeCustosId` bigint,
	`contaId` bigint,
	`empresaId` bigint,
	`empresaNome` varchar(100),
	`collectedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `accounts_receivable_id` PRIMARY KEY(`id`)
);
