CREATE TABLE `cobranca_planilha` (
	`id` int AUTO_INCREMENT NOT NULL,
	`empresa` varchar(500) NOT NULL,
	`descricao` text,
	`cnpj_cpf` varchar(30),
	`municipio` varchar(200),
	`uf` varchar(5),
	`pais` varchar(50),
	`centro_custos` varchar(50),
	`valor` decimal(18,2),
	`vencimento` varchar(10),
	`dias_vencidos` int,
	`tipo` varchar(50),
	`status` varchar(50) NOT NULL DEFAULT 'Pendente',
	`promessa_pgto` text,
	`primeira_cobranca` text,
	`sem_acao_1` text,
	`segunda_cobranca` text,
	`sem_acao_2` text,
	`terceira_cobranca` text,
	`sem_acao_3` text,
	`acao_final` text,
	`observacoes` text,
	`updated_by` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cobranca_planilha_id` PRIMARY KEY(`id`)
);
