CREATE TABLE `vendor_clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`seller_id` int NOT NULL,
	`seller_name` varchar(200) NOT NULL,
	`cnpj_cpf` varchar(20) NOT NULL,
	`razao_social` varchar(300) NOT NULL,
	`nome_fantasia` varchar(300),
	`inscricao_estadual` varchar(30),
	`cep` varchar(10),
	`logradouro` varchar(300),
	`numero` varchar(20),
	`complemento` varchar(200),
	`bairro` varchar(200),
	`cidade` varchar(200),
	`uf` varchar(2),
	`telefone1` varchar(30),
	`telefone2` varchar(30),
	`email` varchar(300),
	`nome_contato` varchar(200),
	`segmento` varchar(100),
	`observacoes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendor_clients_id` PRIMARY KEY(`id`)
);
