CREATE TABLE `import_po_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`po_id` int NOT NULL,
	`description` text NOT NULL,
	`product_code` varchar(20),
	`ncm` varchar(15),
	`unid_caixa` decimal(8,2),
	`valor_usd` decimal(10,4),
	`valor_ci_usd` decimal(10,4),
	`valor_po_cheia` decimal(10,4),
	`valor_po_menor` decimal(10,4),
	`quantidade` int,
	`valor_referencia` decimal(14,2),
	`perc_representatividade` decimal(8,6),
	`valor_caixa_brl` decimal(10,2),
	`preco_mil_unid` decimal(10,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `import_po_products_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `import_pos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplier_id` int NOT NULL,
	`po_number` varchar(20) NOT NULL,
	`container_name` varchar(100),
	`import_number` varchar(50),
	`pagamento_1` decimal(14,2),
	`pagamento_2` decimal(14,2),
	`pagamento_3` decimal(14,2),
	`despesas_liberacao` decimal(14,2),
	`frete_sp_mg` decimal(14,2),
	`custos_sco` decimal(14,2),
	`total_custos_importacao` decimal(14,2),
	`valor_total_produtos_usd` decimal(14,2),
	`valor_frete_maritimo` decimal(14,2),
	`total_commercial_invoice` decimal(14,2),
	`valor_dolar_1` decimal(8,4),
	`valor_dolar_2` decimal(8,4),
	`valor_dolar_3` decimal(8,4),
	`valor_medio_dolar` decimal(8,4),
	`valor_fator` decimal(8,4),
	`status` varchar(30) DEFAULT 'arrived',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `import_pos_id` PRIMARY KEY(`id`)
);
