CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`seller_id` int NOT NULL,
	`seller_name` varchar(200) NOT NULL,
	`status` varchar(30) NOT NULL DEFAULT 'rascunho',
	`cnpj_cpf` varchar(20),
	`razao_social` varchar(300) NOT NULL,
	`nome_fantasia` varchar(300),
	`inscricao_estadual` varchar(30),
	`cep` varchar(10),
	`endereco` varchar(300),
	`numero` varchar(20),
	`bairro` varchar(100),
	`municipio` varchar(100),
	`uf` varchar(2),
	`telefone` varchar(30),
	`email_contato` varchar(200),
	`endereco_entrega_diferente` boolean DEFAULT false,
	`entrega_cep` varchar(10),
	`entrega_logradouro` varchar(300),
	`entrega_numero` varchar(20),
	`entrega_bairro` varchar(100),
	`entrega_cidade` varchar(100),
	`entrega_uf` varchar(2),
	`forma_pagamento` varchar(50),
	`meio_pagamento` varchar(50),
	`condicao_pagamento` varchar(100),
	`valor_frete` decimal(18,2),
	`tipo_frete` varchar(10),
	`transportadora` varchar(200),
	`observacoes` text,
	`validade_dias` int DEFAULT 30,
	`data_validade` varchar(10),
	`items` json NOT NULL,
	`total_produtos` decimal(18,2) NOT NULL,
	`total_pedido` decimal(18,2) NOT NULL,
	`pdf_url` text,
	`converted_to_order_id` int,
	`converted_at` timestamp,
	`operator_id` int,
	`operator_name` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
